"""
Django settings for WorkTrack project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Check if running on cloud (Render, Heroku, etc.)
# Render sets DATABASE_URL, so we can check for that or use a custom env var
ON_CLOUD = os.environ.get('ON_CLOUD') == 'true' or bool(os.environ.get('DATABASE_URL'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3q1fmi)f2b^unqov=8#bhcbfd_y_4k_o6lrlt3p3j5h#!28yzq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not ON_CLOUD

ALLOWED_HOSTS = []
if ON_CLOUD:
    # Allow Render domain - check environment variables first
    render_service_url = os.environ.get('RENDER_EXTERNAL_URL', '')
    render_service_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
    backend_url = os.environ.get('BACKEND_URL', '')

    allowed_hosts = []
    if render_service_url:
        # Extract hostname from URL
        from urllib.parse import urlparse
        parsed = urlparse(render_service_url)
        if parsed.hostname:
            allowed_hosts.append(parsed.hostname)
    if render_service_hostname:
        allowed_hosts.append(render_service_hostname)
    if backend_url:
        from urllib.parse import urlparse
        parsed = urlparse(backend_url)
        if parsed.hostname:
            allowed_hosts.append(parsed.hostname)

    # Always add the specific Render domain
    allowed_hosts.append('worktrack-backend-a4ix.onrender.com')

    ALLOWED_HOSTS = list(set(allowed_hosts))  # Remove duplicates
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "WorkTrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "WorkTrack.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if ON_CLOUD and os.environ.get('DATABASE_URL'):
    database_url = os.environ.get('DATABASE_URL')
    try:
        DATABASES = {
            'default': dj_database_url.parse(database_url)
        }
    except (ValueError, Exception):
        import re
        pattern = r'postgresql://(?:([^:]+):([^@]+)@)?([^:/]+)(?::(\d+))?/(.+)'
        match = re.match(pattern, database_url)
        if match:
            username, password, host, port, database = match.groups()
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': database,
                    'USER': username or 'postgres',
                    'PASSWORD': password or '',
                    'HOST': host,
                    'PORT': int(port) if port else 5432,
                }
            }
        else:
            # Fallback: manual parsing
            url_without_scheme = database_url.replace('postgresql://', '')
            if '@' in url_without_scheme:
                creds, host_part = url_without_scheme.rsplit('@', 1)
                if ':' in creds:
                    username, password = creds.split(':', 1)
                else:
                    username, password = creds, ''
            else:
                username, password = '', ''
                host_part = url_without_scheme
            if '/' in host_part:
                host_port, database = host_part.split('/', 1)
            else:
                host_port, database = host_part, 'postgres'
            if ':' in host_port:
                host, port = host_port.rsplit(':', 1)
                port = int(port)
            else:
                host, port = host_port, 5432
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': database,
                    'USER': username or 'postgres',
                    'PASSWORD': password or '',
                    'HOST': host,
                    'PORT': port,
                }
            }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files
if ON_CLOUD:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS configuration for React frontend
if ON_CLOUD:
    frontend_url = os.environ.get('FRONTEND_URL', '')
    CORS_ALLOWED_ORIGINS = [frontend_url] if frontend_url else []
    backend_url = os.environ.get('BACKEND_URL', '')
    if backend_url and frontend_url:
        CSRF_TRUSTED_ORIGINS = [frontend_url, backend_url]
    elif frontend_url:
        CSRF_TRUSTED_ORIGINS = [frontend_url]
    elif backend_url:
        CSRF_TRUSTED_ORIGINS = [backend_url]
    else:
        CSRF_TRUSTED_ORIGINS = []

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True  # Keep session alive on every request
SESSION_COOKIE_NAME = 'sessionid'
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to read it
